In [1]:
import requests
from json import dumps # для красивого вывода json
import pandas as pd
import fastparquet
#import apimoex
#import pyarrow

### Задание

Необходимо загрузить данные и создать все сопутствующие для этого объекты для реализации витрины (внутренняя таблица в GreenPlum) следующего вида:

Найти самые крупные сделки для конкретной акции для каждого типа (BUY / SELL) в разрезе дня
|Наименование поля|Описание|
| :---: | :---: |
|BOARDID |ID режима торгов|
|BOARD_NAME|Наименование режима торгов|
|ISIN|ISIN код|
|ISQUALIFIEDINVESTORS|Признак предназачена ли бумага для квалифицированных инвесторов|
|SECID|ID акции|
|PRICE|Цена|
|VALUE|Сумма сделки|
|QUANTITY|Кол-во|
|DEAL_TYPE|Тип сделки (BUY / SELL)|
|DEAL_TIME|Время осуществления сделки|
|TRADE_SESSION_DATE|Дата сессии|

### Решение

Согласно источникам
- [Реестр сделок](https://www.moex.com/ru/marketdata/archive/#/engine=stock&market=shares&data_type=trades&data_interval=current&data_format=csv&year=2026)
- [Информационные продукты MOEX](https://www.moex.com/ru/orders?realtime)
- [Итоги торгов](https://www.moex.com/ru/marketdata/#/mode=groups&group=4&collection=3&boardgroup=57&data_type=history&date=2026-06-03&category=main)

скачивание данных о сделках с вэб-сайта MOEX возможно только по платной подписке. При этом, можно ознакомиться с содержание данных о сделках в документации:

- [Описание состава и формата данных](https://www.moex.com/ru/documents/opisanie-sostava-i-formata-dannyh)

Согласно источникам

- [Инструменты фондового рынка](https://www.moex.com/msn/stock-instruments#/)
- [Таблица соответствия торгуемых ценных бумаг по режимам торгов](https://www.moex.com/ru/SecuritiesListing.aspx)

акции могут торговаться в следующих режимах

|PRIMARY_BOARDID|PRIMARY_BOARD_TITLE|
| :---: | :---: |
|TQBR|Т+: Акции и ДР - безадрес.|
|MTQR|ОТС: Акции Т+ - безадресные|
|MPTR|ОТС: Акции РПС с ЦК - адресные|
|RPEY|РЕПО в ин.валюте (CNY) - адрес.|
|LIQR|РЕПО с ЦК: Урегулирование - безадрес.|
|FQBR|Т+ Ин.Акции и ДР|
|FSEQ|РПС: Ин.Акции|
|FTEQ|РПС с ЦК: Ин.Акции и ДР|
|PSEQ|РПС : Акции|
|PTEQ|РПС с ЦК: Акции и ДР|
|SPEQ|Поставка по СК (акции)|
|TQDP|Крупные пакеты - Акции|
|PSPI|РПС Акции ПИР|
|PTPI|РПС с ЦК Акции ПИР|
|TQPI|Т+ Акции ПИР|
|PTSD|РПС с ЦК: Акции и ДР(расч.USD)|


Согласно источнику [Orders of "Book or cancel" type on the stock market](https://www.moex.com/n52316?nt=209), существует еще ряд режимов торгов акциями:

|PRIMARY_BOARDID|PRIMARY_BOARD_TITLE|
| :---: | :---: |
|SMAL|T+: Odd lot trading|
|TQBD|T+: FRGN stocks, DRs USD|
|TQBE|T+: Shares and DRs EUR|
|TQIF|T+: investment funds|
|TQTC|T+: ETC|
|TQTD|T+: ETF USD|
|TQTE|T+: ETF EUR|
|TQTF|T+: ETF|
|FQDE|T+: inv. risk stocks FRGN|
|TQFD|T+: Inv. funds USD|
|TQFE|T+: Inv. funds EUR|
|TQPD|T+ stocks inv. Risk USD|
|TQPE|T+ stocks inv. Risk EUR|
|TQDD|T+: inv. risk stocks FRGN USD|

Перечисленные режимы официально существуют, но их функциональность в текущих условиях санкций на биржу, клиринговый центр и НРД сильно ограничена или полностью парализована.

Важно отметить, что secid со временем может меняться [Информация по изменению торговых кодов бумаг](https://www.moex.com/ru/SecuritiesListing.aspx).

Для получения данных о сделках используем [MOEX ISS API](https://iss.moex.com/iss/reference/), а именно [Все сделки рынка](https://iss.moex.com/iss/reference/379).
Используем параметр `date` - для выгрузки истории сделок за нужный торговый день (2026-06-04). Максимальное значение выгружаемых строк = 5000. Сделки возвращаются в порядке их заключения. Напишем цикл для извлечения всех сделок торгового дня (с использованием параметр `tradeno` - номер сделки, с которого следует начать возвращать данные.).

In [2]:
# считываем первые 5000 строк
res = requests.get('https://iss.moex.com//iss/history/engines/stock/markets/shares/trades.json?date=2026-06-04')
df_res = pd.DataFrame(res.json()["trades"]["data"], columns = res.json()["trades"]["columns"])
print(df_res.head(1))
print(df_res.tail(1))
print(df_res.shape[0])

# определяем номер последней сделки в считанных данных
last_tradeno = df_res.loc[4999, 'TRADENO']
print(last_tradeno)

i=0
df = df_res
while df.shape[0] == 5000:
    # считываем следующие 5000 строк
    res = requests.get(f'https://iss.moex.com//iss/history/engines/stock/markets/shares/trades.json?date=2026-06-04&tradeno={last_tradeno}')
    df = pd.DataFrame(res.json()["trades"]["data"], columns = res.json()["trades"]["columns"])
    i += 1
    # определяем номер последней сделки
    last_tradeno = df.loc[df.shape[0]-1, 'TRADENO']
    # добавляем новые сделки к результирующему датафрейму
    df_res = pd.concat([df_res, df])
    # проверка
    print(i, df.loc[0, 'TRADENO'], last_tradeno, df.shape[0], df_res.shape[0], df.loc[0, 'TRADETIME'], df.loc[df.shape[0]-1, 'TRADETIME'])

       TRADENO   TRADEDATE TRADETIME SECID BOARDID   PRICE  QUANTITY  VALUE  \
0  16659452650  2026-06-04  06:53:13  FIXR    SMAL  0.5094       158  80.49

   TYPE BUYSELL  TRADINGSESSION TRADE_SESSION_DATE
0  None       B               0         2026-06-04
          TRADENO   TRADEDATE TRADETIME SECID BOARDID  PRICE  QUANTITY  \
4999  16659458668  2026-06-04  07:00:00  ROSN    TQBR  396.5         3

       VALUE  TYPE BUYSELL  TRADINGSESSION TRADE_SESSION_DATE
4999  1189.5  None       B               0         2026-06-04
5000
16659458668
1 16659458669 16659464684 5000 10000 07:00:00 07:01:57
2 16659464685 16659470238 5000 15000 07:01:57 07:04:24
3 16659470240 16659475655 5000 20000 07:04:25 07:06:41
4 16659475656 16659481292 5000 25000 07:06:41 07:09:15
5 16659481293 16659487039 5000 30000 07:09:15 07:13:12
6 16659487040 16659493083 5000 35000 07:13:12 07:18:13
7 16659493084 16659500632 5000 40000 07:18:13 07:21:49
8 16659500633 16659506223 5000 45000 07:21:49 07:25:02
9 16659506224 16659512466 5000 50000 07:25:02 07:30:30
10 16659512469 16659519103 5000 55000 07:30:30 07:37:11
11 16659519104 16659525273 5000 60000 07:37:11 07:43:25
12 16659525274 16659531664 5000 65000 07:43:25 07:50:49
13 16659531666 16659537926 5000 70000 07:50:50 07:57:35
14 16659537927 16659544664 5000 75000 07:57:35 08:05:17
15 16659544665 16659550777 5000 80000 08:05:17 08:10:17
16 16659550778 16659556974 5000 85000 08:10:17 08:15:32
17 16659556975 16659562580 5000 90000 08:15:32 08:17:52
18 16659562581 16659568515 5000 95000 08:17:52 08:21:04
19 16659568523 16659574451 5000 100000 08:21:04 08:25:02
20 16659574452 16659580152 5000 105000 08:25:02 08:28:07
21 16659580153 16659586198 5000 110000 08:28:07 08:32:25
22 16659586199 16659592411 5000 115000 08:32:25 08:37:38
23 16659592412 16659598649 5000 120000 08:37:38 08:43:00
24 16659598650 16659604813 5000 125000 08:43:00 08:47:38
25 16659604815 16659611273 5000 130000 08:47:38 08:52:56
26 16659611274 16659617822 5000 135000 08:52:56 08:59:11
27 16659617823 16659623410 5000 140000 08:59:11 09:01:07
28 16659623411 16659628944 5000 145000 09:01:07 09:03:31
29 16659628945 16659634792 5000 150000 09:03:31 09:06:21
30 16659634793 16659640448 5000 155000 09:06:21 09:08:17
31 16659640449 16659646109 5000 160000 09:08:17 09:10:06
32 16659646110 16659652073 5000 165000 09:10:06 09:12:42
33 16659652074 16659657959 5000 170000 09:12:42 09:15:38
34 16659657960 16659663722 5000 175000 09:15:38 09:17:52
35 16659663723 16659669807 5000 180000 09:17:52 09:20:59
36 16659669808 16659676044 5000 185000 09:20:59 09:24:54
37 16659676045 16659682185 5000 190000 09:24:54 09:28:26
38 16659682186 16659688484 5000 195000 09:28:26 09:32:27
39 16659688485 16659694661 5000 200000 09:32:27 09:36:48
40 16659694662 16659700787 5000 205000 09:36:48 09:40:32
41 16659700790 16659707118 5000 210000 09:40:32 09:44:51
42 16659707120 16659713501 5000 215000 09:44:51 09:49:22
43 16659713502 16659719740 5000 220000 09:49:22 09:52:21
44 16659719741 16659725782 5000 225000 09:52:21 09:55:13
45 16659725783 16659733099 5000 230000 09:55:14 09:59:05
46 16659733100 16659738635 5000 235000 09:59:05 10:00:13
47 16659738636 16659743896 5000 240000 10:00:13 10:00:31
48 16659743897 16659749371 5000 245000 10:00:31 10:01:04
49 16659749372 16659754717 5000 250000 10:01:04 10:01:41
50 16659754718 16659760501 5000 255000 10:01:41 10:03:05
51 16659760502 16659766642 5000 260000 10:03:05 10:04:45
52 16659766643 16659773516 5000 265000 10:04:46 10:06:34
53 16659773517 16659781910 5000 270000 10:06:34 10:08:57
54 16659781911 16659789078 5000 275000 10:08:57 10:10:23
55 16659789079 16659796732 5000 280000 10:10:23 10:12:19
56 16659796733 16659804322 5000 285000 10:12:19 10:14:16
57 16659804323 16659811186 5000 290000 10:14:16 10:15:41
58 16659811187 16659818106 5000 295000 10:15:41 10:16:45
59 16659818111 16659824923 5000 300000 10:16:45 10:17:55
60 16659824924 16659831485 5000 305000 10:17:55 10:19:43
61 16659831486 16659838481 5000 310000 10:19:43 10:20:26
62 16659838482 16659844448 5000 315000 10:20:26 10:20:54
63 16659844449 16659849849 5000 320000 10:20:54 10:21:20
64 16659849850 16659855160 5000 325000 10:21:20 10:21:40
65 16659855161 16659860668 5000 330000 10:21:40 10:22:06
66 16659860669 16659866054 5000 335000 10:22:06 10:22:38
67 16659866055 16659871420 5000 340000 10:22:38 10:23:05
68 16659871421 16659876855 5000 345000 10:23:05 10:23:34
69 16659876856 16659882371 5000 350000 10:23:34 10:24:03
70 16659882372 16659887413 5000 355000 10:24:03 10:24:06
71 16659887414 16659892413 5000 360000 10:24:06 10:24:06
72 16659892414 16659897576 5000 365000 10:24:06 10:24:20
73 16659897577 16659902882 5000 370000 10:24:20 10:24:39
74 16659902883 16659908479 5000 375000 10:24:39 10:25:07
75 16659908480 16659913911 5000 380000 10:25:07 10:25:36
76 16659913912 16659919369 5000 385000 10:25:36 10:26:05
77 16659919370 16659924818 5000 390000 10:26:05 10:26:32
78 16659924819 16659930195 5000 395000 10:26:32 10:26:58
79 16659930196 16659935571 5000 400000 10:26:58 10:27:26
80 16659935572 16659941002 5000 405000 10:27:26 10:27:57
81 16659941003 16659946617 5000 410000 10:27:57 10:28:30
82 16659946618 16659951948 5000 415000 10:28:30 10:28:56
83 16659951949 16659958042 5000 420000 10:28:56 10:29:29
84 16659958043 16659963606 5000 425000 10:29:29 10:30:02
85 16659963607 16659969186 5000 430000 10:30:02 10:30:34
86 16659969187 16659974869 5000 435000 10:30:34 10:31:07
87 16659974870 16659980319 5000 440000 10:31:07 10:31:42
88 16659980320 16659985878 5000 445000 10:31:42 10:32:14
89 16659985879 16659991351 5000 450000 10:32:14 10:32:46
90 16659991352 16659996914 5000 455000 10:32:46 10:33:19
91 16659996915 16660002602 5000 460000 10:33:19 10:33:52
92 16660002603 16660008176 5000 465000 10:33:52 10:34:25
93 16660008177 16660013596 5000 470000 10:34:25 10:34:55
94 16660013597 16660019130 5000 475000 10:34:55 10:35:28
95 16660019131 16660024580 5000 480000 10:35:28 10:35:57
96 16660024582 16660030077 5000 485000 10:35:57 10:36:32
97 16660030078 16660035586 5000 490000 10:36:32 10:37:05
98 16660035587 16660041050 5000 495000 10:37:05 10:37:40
99 16660041051 16660046622 5000 500000 10:37:40 10:38:12
100 16660046623 16660052019 5000 505000 10:38:12 10:38:46
101 16660052020 16660057465 5000 510000 10:38:46 10:39:18
102 16660057466 16660062862 5000 515000 10:39:18 10:39:50
103 16660062863 16660068266 5000 520000 10:39:50 10:40:20
104 16660068267 16660073666 5000 525000 10:40:20 10:40:52
105 16660073667 16660079050 5000 530000 10:40:52 10:41:21
106 16660079051 16660084472 5000 535000 10:41:21 10:41:53
107 16660084474 16660090071 5000 540000 10:41:53 10:42:43
108 16660090074 16660097012 5000 545000 10:42:43 10:44:45
109 16660097013 16660103694 5000 550000 10:44:45 10:46:35
110 16660103695 16660109872 5000 555000 10:46:35 10:48:05
111 16660109873 16660116092 5000 560000 10:48:05 10:49:29
112 16660116093 16660122293 5000 565000 10:49:29 10:50:51
113 16660122294 16660128991 5000 570000 10:50:51 10:52:37
114 16660128992 16660136853 5000 575000 10:52:38 10:55:05
115 16660136854 16660143597 5000 580000 10:55:05 10:56:57
116 16660143598 16660150415 5000 585000 10:56:57 10:58:53
117 16660150416 16660156614 5000 590000 10:58:53 11:00:12
118 16660156615 16660163051 5000 595000 11:00:12 11:01:29
119 16660163052 16660169521 5000 600000 11:01:29 11:03:09
120 16660169522 16660175841 5000 605000 11:03:09 11:04:52
121 16660175842 16660182544 5000 610000 11:04:52 11:06:52
122 16660182545 16660188793 5000 615000 11:06:52 11:08:21
123 16660188794 16660195425 5000 620000 11:08:21 11:10:04
124 16660195426 16660201985 5000 625000 11:10:04 11:11:47
125 16660201986 16660207668 5000 630000 11:11:47 11:12:57
126 16660207669 16660214460 5000 635000 11:12:57 11:14:48
127 16660214462 16660220680 5000 640000 11:14:48 11:16:26
128 16660220681 16660227273 5000 645000 11:16:26 11:18:12
129 16660227275 16660233650 5000 650000 11:18:12 11:20:05
130 16660233651 16660239601 5000 655000 11:20:05 11:21:52
131 16660239602 16660245694 5000 660000 11:21:52 11:23:26
132 16660245695 16660251379 5000 665000 11:23:26 11:24:25
133 16660251380 16660258476 5000 670000 11:24:25 11:26:07
134 16660258477 16660264711 5000 675000 11:26:07 11:28:12
135 16660264712 16660270609 5000 680000 11:28:12 11:29:28
136 16660270610 16660276738 5000 685000 11:29:28 11:31:16
137 16660276739 16660282620 5000 690000 11:31:16 11:32:34
138 16660282621 16660288071 5000 695000 11:32:34 11:33:13
139 16660288072 16660293455 5000 700000 11:33:13 11:33:42
140 16660293456 16660301620 5000 705000 11:33:42 11:34:52
141 16660301623 16660309894 5000 710000 11:34:52 11:36:49
142 16660309895 16660320150 5000 715000 11:36:49 11:39:22
143 16660320151 16660327118 5000 720000 11:39:22 11:41:40
144 16660327119 16660333433 5000 725000 11:41:40 11:43:47
145 16660333434 16660339664 5000 730000 11:43:47 11:45:35
146 16660339665 16660345864 5000 735000 11:45:35 11:47:29
147 16660345865 16660352416 5000 740000 11:47:29 11:49:28
148 16660352417 16660358845 5000 745000 11:49:28 11:51:05
149 16660358846 16660365029 5000 750000 11:51:05 11:52:36
150 16660365030 16660370866 5000 755000 11:52:36 11:53:43
151 16660370867 16660377002 5000 760000 11:53:43 11:55:14
152 16660377005 16660382942 5000 765000 11:55:14 11:56:33
153 16660382943 16660388664 5000 770000 11:56:33 11:57:34
154 16660388666 16660394029 5000 775000 11:57:34 11:58:16
155 16660394031 16660400137 5000 780000 11:58:16 11:59:30
156 16660400138 16660406129 5000 785000 11:59:30 12:00:31
157 16660406130 16660412113 5000 790000 12:00:31 12:02:02
158 16660412114 16660418411 5000 795000 12:02:02 12:03:53
159 16660418412 16660424737 5000 800000 12:03:53 12:06:08
160 16660424738 16660431123 5000 805000 12:06:08 12:08:16
161 16660431124 16660437469 5000 810000 12:08:16 12:09:42
162 16660437470 16660444095 5000 815000 12:09:42 12:11:33
163 16660444096 16660450493 5000 820000 12:11:33 12:13:43
164 16660450494 16660456894 5000 825000 12:13:43 12:15:42
165 16660456895 16660463572 5000 830000 12:15:42 12:18:00
166 16660463573 16660470301 5000 835000 12:18:00 12:20:16
167 16660470302 16660475594 5000 840000 12:20:16 12:20:51
168 16660475595 16660480887 5000 845000 12:20:51 12:21:26
169 16660480888 16660486258 5000 850000 12:21:26 12:22:00
170 16660486259 16660491660 5000 855000 12:22:00 12:22:37
171 16660491661 16660496987 5000 860000 12:22:37 12:23:09
172 16660496988 16660502309 5000 865000 12:23:09 12:23:41
173 16660502310 16660507635 5000 870000 12:23:41 12:24:15
174 16660507636 16660513001 5000 875000 12:24:15 12:24:48
175 16660513002 16660518438 5000 880000 12:24:48 12:25:27
176 16660518439 16660523901 5000 885000 12:25:27 12:26:04
177 16660523902 16660529415 5000 890000 12:26:04 12:26:38
178 16660529416 16660534701 5000 895000 12:26:38 12:27:12
179 16660534702 16660541553 5000 900000 12:27:12 12:27:46
180 16660541554 16660547143 5000 905000 12:27:46 12:28:23
181 16660547144 16660552558 5000 910000 12:28:23 12:28:58
182 16660552559 16660557933 5000 915000 12:28:58 12:29:34
183 16660557934 16660563479 5000 920000 12:29:34 12:30:12
184 16660563480 16660568996 5000 925000 12:30:12 12:30:49
185 16660568997 16660574365 5000 930000 12:30:49 12:31:16
186 16660574366 16660579746 5000 935000 12:31:16 12:31:51
187 16660579747 16660585234 5000 940000 12:31:51 12:32:25
188 16660585235 16660590559 5000 945000 12:32:25 12:33:00
189 16660590560 16660595963 5000 950000 12:33:00 12:33:41
190 16660595964 16660601368 5000 955000 12:33:41 12:34:18
191 16660601369 16660606707 5000 960000 12:34:18 12:34:51
192 16660606708 16660612200 5000 965000 12:34:51 12:35:36
193 16660612202 16660619405 5000 970000 12:35:36 12:37:53
194 16660619406 16660625823 5000 975000 12:37:53 12:40:08
195 16660625824 16660631516 5000 980000 12:40:08 12:41:10
196 16660631517 16660638151 5000 985000 12:41:10 12:43:14
197 16660638153 16660644196 5000 990000 12:43:14 12:45:02
198 16660644198 16660650725 5000 995000 12:45:02 12:47:09
199 16660650726 16660657264 5000 1000000 12:47:09 12:48:52
200 16660657265 16660663864 5000 1005000 12:48:52 12:51:23
201 16660663865 16660670357 5000 1010000 12:51:23 12:53:36
202 16660670358 16660676938 5000 1015000 12:53:36 12:56:06
203 16660676939 16660683810 5000 1020000 12:56:06 12:59:02
204 16660683811 16660690309 5000 1025000 12:59:02 13:01:14
205 16660690310 16660697157 5000 1030000 13:01:14 13:04:00
206 16660697159 16660704316 5000 1035000 13:04:00 13:06:15
207 16660704318 16660711171 5000 1040000 13:06:15 13:08:01
208 16660711172 16660718697 5000 1045000 13:08:01 13:10:27
209 16660718698 16660725862 5000 1050000 13:10:27 13:12:44
210 16660725863 16660732617 5000 1055000 13:12:44 13:15:26
211 16660732618 16660738847 5000 1060000 13:15:26 13:17:17
212 16660738848 16660745812 5000 1065000 13:17:17 13:19:18
213 16660745813 16660751985 5000 1070000 13:19:18 13:21:02
214 16660751986 16660758826 5000 1075000 13:21:02 13:23:06
215 16660758827 16660767262 5000 1080000 13:23:06 13:25:06
216 16660767263 16660773499 5000 1085000 13:25:06 13:27:08
217 16660773500 16660780565 5000 1090000 13:27:08 13:29:49
218 16660780566 16660788002 5000 1095000 13:29:49 13:32:31
219 16660788003 16660794633 5000 1100000 13:32:31 13:34:54
220 16660794634 16660799796 5000 1105000 13:34:54 13:35:11
221 16660799797 16660805803 5000 1110000 13:35:11 13:36:35
222 16660805804 16660811770 5000 1115000 13:36:35 13:37:21
223 16660811771 16660817472 5000 1120000 13:37:21 13:38:02
224 16660817473 16660823247 5000 1125000 13:38:02 13:38:35
225 16660823248 16660829206 5000 1130000 13:38:35 13:39:01
226 16660829207 16660834849 5000 1135000 13:39:01 13:39:46
227 16660834850 16660840682 5000 1140000 13:39:46 13:40:36
228 16660840683 16660847227 5000 1145000 13:40:36 13:42:10
229 16660847228 16660854045 5000 1150000 13:42:10 13:44:05
230 16660854046 16660864036 5000 1155000 13:44:05 13:46:00
231 16660864037 16660871300 5000 1160000 13:46:00 13:47:53
232 16660871301 16660883762 5000 1165000 13:47:53 13:49:51
233 16660883765 16660891305 5000 1170000 13:49:51 13:52:24
234 16660891306 16660897314 5000 1175000 13:52:24 13:54:22
235 16660897315 16660912036 5000 1180000 13:54:22 13:56:15
236 16660912037 16660919405 5000 1185000 13:56:15 13:58:40
237 16660919406 16660925568 5000 1190000 13:58:40 14:00:02
238 16660925569 16660931750 5000 1195000 14:00:02 14:01:14
239 16660931751 16660939132 5000 1200000 14:01:14 14:02:35
240 16660939133 16660947257 5000 1205000 14:02:35 14:03:46
241 16660947261 16660952870 5000 1210000 14:03:46 14:04:34
242 16660952871 16660957942 5000 1215000 14:04:34 14:04:39
243 16660957943 16660963126 5000 1220000 14:04:39 14:04:52
244 16660963127 16660968567 5000 1225000 14:04:52 14:05:19
245 16660968568 16660974139 5000 1230000 14:05:19 14:05:59
246 16660974140 16660979382 5000 1235000 14:05:59 14:06:18
247 16660979383 16660984604 5000 1240000 14:06:18 14:06:35
248 16660984605 16660989880 5000 1245000 14:06:35 14:06:56
249 16660989881 16660995007 5000 1250000 14:06:56 14:07:07
250 16660995008 16661000488 5000 1255000 14:07:07 14:07:43
251 16661000489 16661005843 5000 1260000 14:07:43 14:08:11
252 16661005844 16661012047 5000 1265000 14:08:11 14:09:39
253 16661012048 16661018013 5000 1270000 14:09:39 14:10:52
254 16661018014 16661023989 5000 1275000 14:10:52 14:12:05
255 16661023991 16661029987 5000 1280000 14:12:05 14:13:10
256 16661029988 16661036409 5000 1285000 14:13:10 14:14:44
257 16661036410 16661043152 5000 1290000 14:14:44 14:16:50
258 16661043154 16661048798 5000 1295000 14:16:50 14:17:43
259 16661048799 16661054979 5000 1300000 14:17:43 14:19:23
260 16661054980 16661061084 5000 1305000 14:19:23 14:20:35
261 16661061085 16661066505 5000 1310000 14:20:35 14:21:05
262 16661066506 16661071879 5000 1315000 14:21:05 14:21:35
263 16661071880 16661077119 5000 1320000 14:21:35 14:21:54
264 16661077120 16661082356 5000 1325000 14:21:54 14:22:14
265 16661082357 16661087872 5000 1330000 14:22:14 14:22:50
266 16661087873 16661093194 5000 1335000 14:22:50 14:23:16
267 16661093195 16661098689 5000 1340000 14:23:16 14:23:48
268 16661098690 16661103942 5000 1345000 14:23:48 14:24:14
269 16661103943 16661109178 5000 1350000 14:24:14 14:24:35
270 16661109179 16661114514 5000 1355000 14:24:35 14:25:08
271 16661114515 16661119864 5000 1360000 14:25:08 14:25:38
272 16661119865 16661125323 5000 1365000 14:25:38 14:26:16
273 16661125324 16661130763 5000 1370000 14:26:16 14:26:46
274 16661130764 16661136048 5000 1375000 14:26:46 14:27:10
275 16661136049 16661141358 5000 1380000 14:27:10 14:27:33
276 16661141359 16661146696 5000 1385000 14:27:33 14:28:06
277 16661146697 16661152031 5000 1390000 14:28:06 14:28:38
278 16661152032 16661157943 5000 1395000 14:28:38 14:30:05
279 16661157944 16661164725 5000 1400000 14:30:05 14:32:38
280 16661164726 16661172161 5000 1405000 14:32:38 14:35:08
281 16661172162 16661177931 5000 1410000 14:35:08 14:35:57
282 16661177932 16661184904 5000 1415000 14:35:57 14:37:55
283 16661184905 16661191983 5000 1420000 14:37:55 14:40:23
284 16661191984 16661203133 5000 1425000 14:40:23 14:43:14
285 16661203136 16661210414 5000 1430000 14:43:14 14:45:27
286 16661210415 16661217986 5000 1435000 14:45:27 14:47:47
287 16661217987 16661225764 5000 1440000 14:47:47 14:50:13
288 16661225765 16661232121 5000 1445000 14:50:13 14:52:13
289 16661232123 16661238857 5000 1450000 14:52:13 14:54:46
290 16661238858 16661245247 5000 1455000 14:54:46 14:56:47
291 16661245248 16661252286 5000 1460000 14:56:47 14:58:37
292 16661252290 16661258309 5000 1465000 14:58:37 15:00:15
293 16661258311 16661264901 5000 1470000 15:00:15 15:02:30
294 16661264904 16661271217 5000 1475000 15:02:30 15:04:22
295 16661271218 16661277398 5000 1480000 15:04:23 15:05:49
296 16661277399 16661283823 5000 1485000 15:05:49 15:07:59
297 16661283824 16661290264 5000 1490000 15:07:59 15:10:15
298 16661290265 16661296964 5000 1495000 15:10:15 15:12:58
299 16661296965 16661303866 5000 1500000 15:12:58 15:15:11
300 16661303867 16661310537 5000 1505000 15:15:11 15:17:24
301 16661310538 16661317280 5000 1510000 15:17:24 15:20:00
302 16661317281 16661323499 5000 1515000 15:20:00 15:21:35
303 16661323500 16661329232 5000 1520000 15:21:35 15:22:36
304 16661329233 16661335912 5000 1525000 15:22:36 15:25:15
305 16661335914 16661361612 5000 1530000 15:25:15 15:27:59
306 16661361613 16661369462 5000 1535000 15:27:59 15:30:57
307 16661369463 16661376310 5000 1540000 15:30:57 15:33:42
308 16661376311 16661384560 5000 1545000 15:33:42 15:36:37
309 16661384561 16661391973 5000 1550000 15:36:37 15:39:56
310 16661391974 16661400311 5000 1555000 15:39:56 15:43:02
311 16661400312 16661442361 5000 1560000 15:43:02 15:46:23
312 16661442362 16661448299 5000 1565000 15:46:23 15:47:47
313 16661448300 16661455806 5000 1570000 15:47:47 15:51:02
314 16661455807 16661462908 5000 1575000 15:51:02 15:54:19
315 16661462909 16661471105 5000 1580000 15:54:19 15:57:14
316 16661471106 16661479038 5000 1585000 15:57:14 16:00:15
317 16661479039 16661485990 5000 1590000 16:00:15 16:02:39
318 16661485991 16661491891 5000 1595000 16:02:39 16:03:50
319 16661491892 16661498753 5000 1600000 16:03:50 16:05:31
320 16661498754 16661505550 5000 1605000 16:05:31 16:08:27
321 16661505553 16661510927 5000 1610000 16:08:27 16:09:10
322 16661510928 16661517186 5000 1615000 16:09:10 16:11:37
323 16661517187 16661524091 5000 1620000 16:11:37 16:14:58
324 16661524092 16661531225 5000 1625000 16:14:58 16:18:32
325 16661531226 16661537799 5000 1630000 16:18:32 16:20:30
326 16661537800 16661543298 5000 1635000 16:20:30 16:21:03
327 16661543299 16661548544 5000 1640000 16:21:03 16:21:33
328 16661548545 16661553899 5000 1645000 16:21:33 16:22:09
329 16661553900 16661559115 5000 1650000 16:22:09 16:22:29
330 16661559116 16661564386 5000 1655000 16:22:29 16:22:57
331 16661564387 16661569894 5000 1660000 16:22:57 16:23:27
332 16661569895 16661575196 5000 1665000 16:23:27 16:23:59
333 16661575198 16661580561 5000 1670000 16:23:59 16:24:33
334 16661580562 16661585872 5000 1675000 16:24:33 16:25:06
335 16661585875 16661591216 5000 1680000 16:25:06 16:25:39

In [3]:
# проверка на дубликаты
print(df_res.shape[0])
print(len(df_res['TRADENO'].unique()))

2641370
2641370

In [4]:
# содержимое поля TRADETIME
df_res.groupby('TRADINGSESSION').agg({'TRADETIME': ['min', 'max']})

               TRADETIME
                     min       max
TRADINGSESSION
0               06:53:13  09:49:58
1               09:50:00  18:59:29
2               19:00:01  23:49:58

In [5]:
# содержимое поля TRADEDATE, TRADE_SESSION_DATE
print(df_res['TRADEDATE'].unique())
print(df_res['TRADE_SESSION_DATE'].unique())

<ArrowStringArray>
['2026-06-04']
Length: 1, dtype: str
<ArrowStringArray>
['2026-06-04']
Length: 1, dtype: str

In [6]:
# отобразим первые строки получившегося датафрейма
display(df_res.head(2))

,TRADENO,TRADEDATE,TRADETIME,SECID,BOARDID,PRICE,QUANTITY,VALUE,TYPE,BUYSELL,TRADINGSESSION,TRADE_SESSION_DATE
0,16659452650,2026-06-04,06:53:13,FIXR,SMAL,0.5094,158,80.49,None,B,0,2026-06-04
1,16659452653,2026-06-04,06:58:14,FIXR,SMAL,0.5234,1,0.52,None,B,0,2026-06-04

In [7]:
# сохраним только нужные колонки
df_res = df_res[['TRADENO', 'TRADE_SESSION_DATE', 'TRADETIME', 'SECID', 'BOARDID', 'PRICE', 'QUANTITY', 'VALUE', 'BUYSELL']]

# отобразим первые строки получившегося датафрейма
display(df_res.head(2))

,TRADENO,TRADE_SESSION_DATE,TRADETIME,SECID,BOARDID,PRICE,QUANTITY,VALUE,BUYSELL
0,16659452650,2026-06-04,06:53:13,FIXR,SMAL,0.5094,158,80.49,B
1,16659452653,2026-06-04,06:58:14,FIXR,SMAL,0.5234,1,0.52,B

In [8]:
# переведем название столбцов в нижний регистр
new_col_name = [v.lower() for v in df_res.columns]
df_res.columns = new_col_name
# отобразим первые строки получившегося датафрейма
display(df_res.head(2))

,tradeno,trade_session_date,tradetime,secid,boardid,price,quantity,value,buysell
0,16659452650,2026-06-04,06:53:13,FIXR,SMAL,0.5094,158,80.49,B
1,16659452653,2026-06-04,06:58:14,FIXR,SMAL,0.5234,1,0.52,B

Сопоствим поля из выгрузки и требуемые по заданию:
|Наименование поля|Описание|В выгрузке|
| :---: | :---: | :---: |
|BOARDID |ID режима торгов|BOARDID|
|BOARD_NAME|Наименование режима торгов||
|ISIN|ISIN код||
|ISQUALIFIEDINVESTORS|Признак предназачена ли бумага для квалифицированных инвесторов||
|SECID|ID акции|SECID|
|PRICE|Цена|PRICE|
|VALUE|Сумма сделки|VALUE|
|QUANTITY|Кол-во|QUANTITY|
|DEAL_TYPE|Тип сделки (BUY / SELL)|BUYSELL|
|DEAL_TIME|Время осуществления сделки|TRADETIME|
|TRADE_SESSION_DATE|Дата сессии|TRADE_SESSION_DATE|

Дополнительно нужно найти [BOARD_NAME](https://iss.moex.com/iss/reference/351), ISIN, ISQUALIFIEDINVESTORS. ISIN, ISQUALIFIEDINVESTORS возьмем с сайта [Список ценных бумаг, допущенных к торгам по состоянию на...](https://www.moex.com/ru/listing/securities-list.aspx), скачаем листинг в csv и сохраним в \data\Export_ru_securities-list_20260605.csv.

In [9]:
# сбор наименований режимов торгов
res_board_name = requests.get('https://iss.moex.com/iss/engines/stock/markets/shares.json?date=2026-06-04')
# print(dumps(res.json(), indent=4, ensure_ascii=False))
df_board_name = pd.DataFrame(res_board_name.json()["boards"]["data"], columns = res_board_name.json()["boards"]["columns"])
display(df_board_name.head(2))
print(df_board_name.shape[0])

,id,board_group_id,boardid,title,is_traded
0,1,6,EQBR,Основной режим: А1-Акции и паи - безадрес.,0
1,2,6,EQBS,Основной режим: А2-Акции и паи - безадрес.,0

35

In [10]:
# сохраним только нужные колонки
df_board_name =  df_board_name[['boardid', 'title']]
display(df_board_name.head(2))

  boardid                                       title
0    EQBR  Основной режим: А1-Акции и паи - безадрес.
1    EQBS  Основной режим: А2-Акции и паи - безадрес.

In [11]:
# сбор isin, isqulifiedinvestors
df_sec = pd.read_csv('data/Export_ru_securities-list_20260605.csv', sep=',', encoding='ANSI')
display(df_sec.head(2))

,DATESTAMP,INSTRUMENT_ID,LIST_SECTION,NPP,SUPERTYPE,INSTRUMENT_TYPE,INSTRUMENT_CATEGORY,TRADE_CODE,ISIN,REGISTRY_NUMBER,...,OTHER_SECURITIES,DISCLOSURE_PART_PAGE,DISCLOSURE_RF_INFO_PAGE,INCLUDE_DATE,CFI_FOREIGN,ISIN_UNDERLYING_ASSET,CFI_UNDERLYING_ASSET,PIF_STATUS,PIF_STATUS_HIST,OBLIGATION_PROGRAM_DATE
0,04.06.2026 00:00:00,15348,Первый уровень,1,Облигации,Облигация биржевая,биржевые облигации процентные неконвертируемые...,NaN,NaN,4B02-02-00354-B-003P,...,"Облигация корпоративная, 41900354B, RU000A0ZZF...",https://www.gazprombank.ru,https://www.e-disclosure.ru/portal/company.asp...,04.06.2021 00:00:00,NaN,NaN,NaN,NaN,NaN,27.08.2018 00:00:00
1,04.06.2026 00:00:00,15349,Первый уровень,2,Облигации,Облигация биржевая,биржевые облигации процентные неконвертируемые...,NaN,NaN,4B02-03-00354-B-003P,...,"Облигация корпоративная, 41900354B, RU000A0ZZF...",https://www.gazprombank.ru,https://www.e-disclosure.ru/portal/company.asp...,04.06.2021 00:00:00,NaN,NaN,NaN,NaN,NaN,27.08.2018 00:00:00

In [12]:
# сохраним только нужные колонки
df_sec = df_sec[['TRADE_CODE', 'ISIN', 'SUPERTYPE', 'QUALIFIED_INVESTOR']] #[df_sec['SUPERTYPE'] == 'Акции']
#переведем название столбцов в нижний регистр
new_col_name = [v.lower() for v in df_sec.columns]
df_sec.columns = new_col_name
# отобразим первые строки получившегося датафрейма
display(df_sec.head(2))

  trade_code isin  supertype qualified_investor
0        NaN  NaN  Облигации                NaN
1        NaN  NaN  Облигации                NaN

In [13]:
#объеденим датафреймы
df_res = df_res.merge(df_board_name, on='boardid', how='left')
df_res = df_res.merge(df_sec, left_on ='secid', right_on='trade_code', how='left')
display(df_res.head(2))
display(df_res.shape[0])

,tradeno,trade_session_date,tradetime,secid,boardid,price,quantity,value,buysell,title,trade_code,isin,supertype,qualified_investor
0,16659452650,2026-06-04,06:53:13,FIXR,SMAL,0.5094,158,80.49,B,Т+: Неполные лоты (акции) - безадрес.,FIXR,RU000A10B5G8,Акции,NaN
1,16659452653,2026-06-04,06:58:14,FIXR,SMAL,0.5234,1,0.52,B,Т+: Неполные лоты (акции) - безадрес.,FIXR,RU000A10B5G8,Акции,NaN

2641370

In [14]:
df_res[df_res['title'].isnull()]

Empty DataFrame
Columns: [tradeno, trade_session_date, tradetime, secid, boardid, price, quantity, value, buysell, title, trade_code, isin, supertype, qualified_investor]
Index: []

In [15]:
df_res[df_res['isin'].isnull()]

Empty DataFrame
Columns: [tradeno, trade_session_date, tradetime, secid, boardid, price, quantity, value, buysell, title, trade_code, isin, supertype, qualified_investor]
Index: []

In [16]:
df_res['supertype'].value_counts()

supertype
Акции                    1758041
Инвестиционные паи        883036
Депозитарные расписки        293
Name: count, dtype: int64

In [17]:
# отфильтруем акции
df_res = df_res[df_res['supertype'] == 'Акции']
# оставим только нужные столбцы
df_res = df_res[['tradeno', 'trade_session_date', 'tradetime', 'secid', 'boardid', 'price', 'quantity', 'value', 'buysell', 'title', 'isin', 'qualified_investor']]
# приведем дату к типу datetime
# df_res['trade_session_date'] = pd.to_datetime(df_res['trade_session_date'])
# отобразим первые строки получившегося датафрейма
display(df_res.head(2))
display(df_res.shape[0])

,tradeno,trade_session_date,tradetime,secid,boardid,price,quantity,value,buysell,title,isin,qualified_investor
0,16659452650,2026-06-04,06:53:13,FIXR,SMAL,0.5094,158,80.49,B,Т+: Неполные лоты (акции) - безадрес.,RU000A10B5G8,NaN
1,16659452653,2026-06-04,06:58:14,FIXR,SMAL,0.5234,1,0.52,B,Т+: Неполные лоты (акции) - безадрес.,RU000A10B5G8,NaN

1758041

In [24]:
len(df_res['tradeno'].unique())

1758041

In [18]:
df_res['boardid'].value_counts()

boardid
TQBR    1754116
SMAL       3925
Name: count, dtype: int64

In [19]:
df_res['buysell'].value_counts()

buysell
B    892339
S    865702
Name: count, dtype: int64

In [20]:
df_res.info()

<class 'pandas.DataFrame'>
Index: 1758041 entries, 0 to 2641369
Data columns (total 12 columns):
 #   Column              Dtype
---  ------              -----
 0   tradeno             int64
 1   trade_session_date  str
 2   tradetime           str
 3   secid               str
 4   boardid             str
 5   price               float64
 6   quantity            int64
 7   value               float64
 8   buysell             str
 9   title               str
 10  isin                str
 11  qualified_investor  str
dtypes: float64(2), int64(2), str(8)
memory usage: 313.4 MB

In [ ]:
#df_res = df_res.reset_index()
df_res = df_res.set_index("tradeno")

In [39]:
display(df_res.head(2))

,trade_session_date,tradetime,secid,boardid,price,quantity,value,buysell,title,isin,qualified_investor
tradeno,,,,,,,,,,,
16659452650,2026-06-04,06:53:13,FIXR,SMAL,0.5094,158,80.49,B,Т+: Неполные лоты (акции) - безадрес.,RU000A10B5G8,NaN
16659452653,2026-06-04,06:58:14,FIXR,SMAL,0.5234,1,0.52,B,Т+: Неполные лоты (акции) - безадрес.,RU000A10B5G8,NaN

In [43]:
df_res.columns

Index(['trade_session_date', 'tradetime', 'secid', 'boardid', 'price',
       'quantity', 'value', 'buysell', 'title', 'isin', 'qualified_investor'],
      dtype='str')

In [44]:
df_res.to_parquet("data/stock_market_securities_20260604.parquet", compression = 'snappy', engine='fastparquet')

In [45]:
# отобразим список тикеров начинающихся на I
sorted(df_res[df_res['secid'].apply(lambda x: x[:1])=="I"]['secid'].unique())

['IGST', 'IGSTP', 'IRAO', 'IRKT', 'IVAT']